sudo: required
dist: trusty

language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

services:
  - docker

env:
  - CLIENT=socket

before_install:
  - docker pull elasticsearch
  - docker pull elubow/cassandra
  - if [ $CLIENT == socket ]; then
      docker pull davebshow/titan-websockets;
    else
      docker pull elubow/titan;
    fi

install:
  - pip install tornado
  - pip install coveralls
  - pip install requests_futures
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install trollius; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install asyncio; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install aiohttp; fi
  - docker run -d --name es1 elasticsearch
  - docker run -d --name cas1 elubow/cassandra
  - if [ $CLIENT == socket ]; then
      docker run -d --name titan1 --link es1:elasticsearch --link cas1:cassandra -p 8182:8182 davebshow/titan-websockets;
    else
      docker run -d --name titan1 --link es1:elasticsearch --link cas1:cassandra -p 8182:8182 elubow/titan;
    fi

before_script:
  - sleep 30

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      coverage run --source=gremlinclient setup.py test -s tests.test_trollius;
      coverage run --source=gremlinclient setup.py test -s tests.test_tornado;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      coverage run --source=gremlinclient setup.py test -s tests.test_tornado;
      coverage run --source=gremlinclient setup.py test -s tests.test_asyncio;
      coverage run --source=gremlinclient setup.py test -s tests.test_aiohttp;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
      coverage run --source=gremlinclient setup.py test -s tests.test_tornado_PEP492;
      coverage run --source=gremlinclient setup.py test -s tests.test_asyncio_PEP492;
      coverage run --source=gremlinclient setup.py test -s tests.test_aiohttp_PEP492;
    fi

after_success:
  - coveralls

after_script:
 - docker stop $(docker ps -a -q)
 - docker rm $(docker ps -a -q)
