sudo: required
dist: trusty

language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

services:
  - docker

before_install:
  - docker pull itzg/elasticsearch
  - docker pull poklet/cassandra
  - docker pull davebshow/titan-websockets

install:
  - pip install tornado
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install trollius; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install asyncio; fi
  - docker run -d --name es1 itzg/elasticsearch
  - docker run -d --name cas1 poklet/cassandra
  - docker run -d -p 8182:8182 -p 8183:8183 -p 8184:8184 --name titan --link es1:elasticsearch --link cas1:cassandra davebshow/titan-websockets

before_script:
  - sleep 10

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python setup.py test -s tests.test_tornado; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python setup.py test -s tests.test_tornado; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python setup.py test -s tests.test_asyncio; fi
