sudo: required
dist: trusty

language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

services:
  - docker

before_install:
  - docker pull elasticsearch
  - docker pull elubow/cassandra
  - docker pull davebshow/titan-websockets

install:
  - pip install tornado
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install trollius; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install asyncio; fi
  - docker run -d --name es1 elasticsearch
  - docker run -d --name cas1 elubow/cassandra
  - docker run -d --name titan1 --link es1:elasticsearch --link cas1:cassandra -p 8182:8182 davebshow/titan-websockets

before_script:
  - sleep 30

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python setup.py test -s tests.test_tornado; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python setup.py test -s tests.test_trollius; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python setup.py test -s tests.test_tornado; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python setup.py test -s tests.test_asyncio; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python setup.py test -s tests.test_tornado _PEP492; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coverage run --source=gremlinclient setup.py test -s tests.test_asyncio_PEP492; fi

after_success:
  - coveralls
  
after_script:
 - docker stop $(docker ps -a -q)
 - docker rm $(docker ps -a -q)
